version: '3'

services:

  sql-db:
    container_name: sql_studienarbeit
    image: mysql:latest
    ports:
      - 3307:3306
    expose:
      - 3307
    environment:
      - MYSQL_ROOT_PASSWORD=ThePassword
      - MYSQL_DATABASE=se_studienarbeit
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=ThePassword
    restart: always
    networks:
      - springboot-mysql
    volumes:
      - ./db:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
      
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://sql-db:3306/se_studienarbeit
      - SPRING_DATASOURCE_USERNAME=springuser
      - SPRING_DATASOURCE_PASSWORD=ThePassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: on-failure
    depends_on:
      sql-db:
        condition: service_started
    networks:
      - springboot-mysql

networks:
  springboot-mysql:
